FROM ruby:3.1.1-buster

ARG DIR=/src
ENV LANG C.UTF-8
ENV BUNDLER_VERSION 2.3.15
ENV FOREMAN_VERSION 0.87.2
ENV ARG_COMPOSE_WAIT_VER 2.9.0

RUN curl -SL https://github.com/ufoscout/docker-compose-wait/releases/download/${ARG_COMPOSE_WAIT_VER}/wait -o /wait
RUN chmod +x /wait

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update -qq \
    && apt-get install --no-install-recommends -y \
    autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libcurl4-openssl-dev libxml2-dev libvips postgresql-client \
    nodejs \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN gem update --system \
    && gem install bundler -v $BUNDLER_VERSION

RUN gem install foreman -v $FOREMAN_VERSION

RUN gem install prettier_print syntax_tree syntax_tree-haml syntax_tree-rbs

RUN mkdir ${DIR}
WORKDIR ${DIR}

RUN useradd -m --shell /bin/bash --uid 1000 ruby
USER ruby

ENV EDITOR vim
ENV BUNDLE_PATH vendor/bundle

RUN bundle config --global retry 5 \
    && bundle config --global path ${BUNDLE_PATH}
